config/routes.rb
Mulakath::Application.routes.draw do
  get "user/profile"

  match 'login/sign_up' => 'login#sign_up'
  match 'login/log_in' => 'login#log_in'
  match 'user/photo' => 'user#photo'
   match 'posts/delete'=>'posts#delete'
  match 'posts/chat_index'=>'posts#chat_index'
  match 'posts/add_wall_post'=>'posts#add_wall_post'
  match 'login/logout' =>'login#logout'
  match 'settings/index' =>'settings#index'
  match 'user/profile' =>'user#profile'
  match 'user/member_profile' =>'user#member_profile'
  resources :posts do
    member do
      post "comment"

    end

  end
  resources :user

   root :to => 'login#log_in'

end

app/models/album.rb
class Album < ActiveRecord::Base
   attr_accessible :avatar, :users_id,:profile_picture ,:avatar_cache
   belongs_to :users
   mount_uploader :avatar, AvatarUploader
end

app/models/chat.rb
class Chat < ActiveRecord::Base
   attr_accessible :user_id, :body
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  #validates :commenter , :presence => true
  validates :message , :presence => true
  attr_accessible :commenter, :message  ,:users_id ,:post_id ,:description
  belongs_to :users
end

app/models/login.rb
class Login < ActiveRecord::Base
   attr_accessible :password,:email,:status

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	#validates :name , :presence => true
	#validates :title , :presence => true
	validates :description , :presence => true
  attr_accessible :name, :title,:description ,:user_id
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  attr_accessible :user_id, :post_id,:security_level,:member_id
end

app/models/users.rb
class Users < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :username, :password,:email,:gender,:date_of_birth,:role ,:status
  def self.authenticate?(email, password)
    u = Users.find_by_email email
    u.password == password
  end
  has_many :comments
  has_many :albums

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    Users.find(session[:user_id]) unless session[:user_id].nil?
  end



end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def log_in
    @status_id=true
    if request.post?

      if params[:login][:email].blank? && params[:login][:password].blank?
        flash.now[:error] = "Please Sign Up Before Login"
      else
        @user = Users.new(params[:login])
        user = Users.find_by_email @user.email

        logger.info("----------#{user.inspect}------------")
        if user and Users.authenticate?(@user.email, @user.password)
          session[:user_id] = user.id
          user.update_attributes(:status=>true)
          #logger.info"mahiya#{session[:user_id].inspect}"
          flash[:notice] = "Welcome, #{user.username}!"
          redirect_to  :controller=>'posts',:action => 'index'
        else
          flash[:notice] = 'Invalid email or password combination'
        end
      end

    end
  end
  def sign_up
    @role_id=1
    @status_id=false
    @login=Users.new(params[:signup])
    if request.post?
      @gen=params[:signup][:gender]
      if @gen=="Male"
        @login.gender=true
      else
        @login.gender=false
      end
      @login.save
      redirect_to  :action => 'log_in'
    end
  end

  def logout
    @stat_value= Users.find(params[:id])
    @stat_value.update_attributes(:status=>false)
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to  :controller=>'login',:action => 'log_in'
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout :choose_layout
  def choose_layout
    return 'dashboard' if action_name == 'chat_index'
    return 'dashboard' if action_name == 'index'
    return 'dashboard' if action_name == 'new'
    return 'dashboard' if action_name == 'show'
  end
  def index
    @posts =Post.order('created_at DESC')

  end

  def show
    if(params[:demo].present?)
      @post=Post.find(params[:id])
      logger.info("this is the text")
      @comment = @post.comments.new(:commenter=>params[:commenter],:message =>params[:message],:users_id=>session[:user_id])
      respond_to do |format|
        if @comment.save
          format.js
        else
          format.html{render :action => "show"}
        end
      end
    else
      @post=Post.find(params[:id])
    end
  end
  def new

    @post =Post.new

  end

  def create

    @post=Post.new(params[:post])
    if @post.save
      redirect_to   posts_path
    else
      render :action => "new"
    end
  end

  def comment

    @post=Post.find(params[:id])
    @comment = @post.comments.create(params[:comment])
    redirect_to  posts_path

  end

  def edit
    @post =Post.find(params[:id])
  end

  def update
    @post =Post.find(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to post_path(@post)
    else
      render :action => "edit"

    end
  end
  def delete
    #@post =Post.find(params[:id])
    @com=Comment.find(params[:id])
    if @com.destroy
      redirect_to  :action => "index"
    end
  end

  def chat_index
    @chats=Chat.all
    @chat=Chat.new(params[:chat])
    if request.post?
      @chat.save
    end
  end
  def add_wall_post
    #@post=Post.find(params[:post_id])
    #@comment = @post.comments.create(params[:comment])
    #redirect_to  post_path(@post)
    respond_to do |format|
      format.js
    end
  end


end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  layout :choose_layout
  def choose_layout
    # return 'dashboard' if action_name == 'profile'
    return 'dashboard' if action_name == 'index'
  end
  def index
  @members=Users.find(:all,:conditions=>:username!='admin')
    if request.post?
      @setting=Setting.new(params[:sett])
      @setting.save
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  layout :choose_layout
  def choose_layout
    return 'dashboard' if action_name == 'profile'
    return 'dashboard' if action_name == 'member_profile'
    return 'dashboard' if action_name == 'photo'
  end
  def profile
    @current_user_id=Users.find_by_id(session[:user_id])
  end
  def member_profile
    @mem_profile=Users.find_by_id(params[:id])
  end

  def photo
    #logger.info("----------#{session[:user_id]}============")
    if request.post?
      @album=Album.new(params[:album])


#@album_check=Album.find_by_users_id_and_profile_picture(session[:user_id],true)
     # if (@album_check.profile_picture==true)
        #@album_check.update_attributes(:profile_picture=>false)
        #@album.users_id=session[:user_id]
        #@album.profile_picture=false
        #@album.save
       # redirect_to :controller=>"user",:action=>"profile"
      #else

        @album.users_id=session[:user_id]
        #@album.profile_picture=false
        @album.save

        logger.info("yessssssssssssssssssssss")
        redirect_to :controller=>"user",:action=>"profile"
      #end
    end
  end
  def profile_sss

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Mulakath</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag :defaults, "jquery-1.5.2.min.js", "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
  <div id="container">
  <div id="header">
    <div style="position: absolute;margin-left: 20px;">
      <img src="../images/mulaqath.jpg"style="width:152px;height:56px;"alt="some_text"/>
    </div>
    <div style="float:right;margin-right: 100px;">
         <% if session[:user_id].nil? %>
          <%=link_to "Login", :action=>"log_in"%>
          <%=link_to "SignUp", :action=>"sign_up"%>
             <% else %>
      <%=link_to"logout",:controller=>'login',:action=>'logout',:id=>session[:user_id] %>

    <%=link_to"Settings",:controller=>'settings',:action=>'index' %>
          <% end %>
      </div>
  </div>


  </div>
</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>


  <title>Mulaqath</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag :defaults, "jquery.js", "application" %>
  <%= csrf_meta_tags %>

  <%= javascript_include_tag 'jquery-1.7.2 ' %>

  <script type="text/javascript">

      $(document).ready(function(){
          $("button").click(function(){
              $("#chat_view").slideToggle();
          });
      });
  </script>
</head>
<body>

 <div id="container">
    <div id="header">
     <div style="position: absolute;margin-left: 20px;">
      <img src="../images/mulaqath.jpg"style="width:152px;height:56px;"alt="some_text"/>

     </div>
      <div style="float: left;margin-left: 200px;">
        <% @cur_user=Users.find_by_id(session[:user_id]) %>
        <h4 style="float: right;color:#FFF;">&nbsp;&nbsp;&nbsp;<%=@cur_user.username %> </h4>
      </div>
      <div style="float:right;margin-right: 100px;">
      <% if session[:user_id].nil? %>
          <%=link_to "Login", :action=>"log_in"%>
          <%=link_to "SignUp", :action=>"sign_up"%>
      <% else %>
             <%=link_to"Home",:controller=>'posts',:action=>'index'%>
            <%=link_to"Profile",:controller=>'user',:action=>'profile' %>
            <%=link_to"Settings",:controller=>'settings',:action=>'index' %>
            <%=link_to"Logout",:controller=>'login',:action=>'logout',:id=>session[:user_id] %>

      <% end %>
      </div>
    </div>
       <div id="user">
         <div style="margin-top:43px;height:120px;width:130px;">
         <% @cur_user=Users.find_by_id(session[:user_id]) %>
         <%@profile_img=Album.find_by_users_id_and_profile_picture(@cur_user.id,true) %>
             <%unless @profile_img.nil?%>
           <%= image_tag @profile_img.avatar %>
               <%end%>
       </div>
       </div>
   <div id="left_box">

   </div>
       <div id="content">

       <%= yield %>

     </div>

   <div id="chat_box">
     <button>click to hide </button>
     <%@active_users= Users.find_all_by_status(true) %>
     <div id="chat_view" >
       <% unless @active_users.nil? %>
     <% @active_users.each do |active| %>
               <% if active.id==session[:user_id] %>
               <%#= active.username %>
               <% else %>
           <%=link_to active.username,:controller=>'user',:action => 'member_profile',:id=>active %><br/>
                  <% end %>
     <% end %>
           <% end %>
     </div>

   </div>

 </div>

</body>
</html>

app/views/login/log_in.erb
<div id="login-cont">
  <div class="signin-wrapper" data-login-message="">
  <h1>Login To Mulaqath</h1>
  <%=form_for :login do |log|%>
      <div style="margin-bottom: 15px;"><div style="width:120px;float: left;">Email</div><%=log.text_field :email%>  </div>
      <div><div style="width:120px;float: left;">Password</div><%=log.password_field :password%></div>  <br/>
      <%=log.hidden_field :status,:value=>@status_id%>

      <%=log.submit "Login",:class=>"button1"%>
  <%end%>


    </div>
</div>

app/views/login/sign_up.erb
<div id="signup_block">
  <h2>New User?&nbsp;Sign Up</h2>
  <div style="text-align: left;line-height: 2.8em;">
    <%=form_for :signup do |log|%>
        <table style="padding: 10px;">
          <tr>
            <td>User Name</td>    <td><%=log.text_field :username%></td>
          </tr>
          <tr>
            <td>Password:</td>    <td><%=log.password_field :password%></td>
          </tr>
          <tr>
            <td>Email:</td>    <td><%=log.text_field :email%></td>
          </tr>
          <tr>
            <td> Gender:</td>    <td>&nbsp;<%=log.select :gender,["Male","Female"],:prompt=>"select any gender"%></td>
          </tr>
          <%=log.hidden_field :role,:value=>@role_id%>
          <%=log.hidden_field :status,:value=>@status_id%>
          <tr>
            <td>Date of Birth:</td>    <td> <%=log.date_select :date_of_birth, :start_year => 1980%></td>
          </tr>
          <tr>
            <td colspan="2"> <%=log.submit "signUp",:class=>"button1"%></td>
          </tr>
        </table>


    <%end%>
  </div>


</div>

app/views/posts/_chats.html.erb
<div style="margin:0px auto;width: 100%;">

  <% @posts.each do |post| %>
      <%=form_for :comment,:url=>{:id=>post.id,:action=>'comment'} do |com|%>
          <li>
            <div class="post_div">

              <%@post_user=Users.find_by_id(post.user_id) %>
              <%unless @post_user.nil? %>
                  <h4 class="poster">
                    <%=link_to @post_user.username,:controller=>'user',:action => 'member_profile',:id=>@post_user.id %> </h4>
                  <small><%= post.description %></small>
              <% end %>
              <div style="margin-top: 10px;">
                <%=com.text_area :message,:rows=>1 %>
                <%=com.hidden_field :post_id,:value=>post.id %>  <br/>
                <%=com.hidden_field :users_id,:value=>session[:user_id] %>
                <%=com.submit "comment"%>
              </div>
              <div style="float:right;">
                <small><%= link_to 'show old comments', post %>
                  &nbsp;<%#= link_to 'Edit comments' , edit_post_path(post) %></small>
              </div>
              <div id="comments_list">
                <% @comme=Comment.where(:post_id=>post.id).order("created_at DESC").limit(3) %>
                <% unless @comme.nil? %>
                    <% @comme.each do |comme| %>
                        <%@commenter=Users.find_by_id(comme.users_id) %>
                        <%unless @commenter.nil?%>
                            <div id="comments">
                              <h4><%=link_to @commenter.username ,:controller=>'user',:action => 'member_profile',:id=>@commenter.id%> </h4>
                        <% end %>
                        <br/>
                        &nbsp;&nbsp;&nbsp;<%= comme.message %><br/>
                        </div>
                    <% end %>
                <% end %>
              </div>
            </div>
          </li>
      <% end %>

  <% end %>


</div>

app/views/posts/_chats_list.html.erb
hiiiiiiiiiiiii
<% unless @chats.nil? %>
<% @chats.each do |chats| %>
    <%= chats.user_id %>
    <%= chats.body %>     <br/>
<% end %>
<% end %>
        </div>

app/views/posts/_comment.erb
  <table id="listing"style="margin-left: 100px;">
    <tr class="tr-head">
      <td>
        commenter:
      </td>
      <td>
        Message
      </td>
    </tr>
    <% @post.comments.each do |comment| %>
    <tr class="tr-even">
      <%@user_name=Users.find(comment.id) %>
      <td><%=@user_name.username %></td>
      <td><%= comment.message %></td>
      <td><%= link_to"delete",:action=>'delete',:id=>comment.id %> </td>
      <% #logger.info"aja aja #{comment.id.inspect}" %>
    </tr>
    <% end %>
  </table>

app/views/posts/_load.html.erb
khamarrrrrrrrrrrrrrrrrr

app/views/posts/add_wall_post.js.erb
/*$("#add_wall_post").append("<%#=Comment.find_all_by_post_id(@post.id).last%>");*/

alert('yo yo');

app/views/posts/chat_index.html.erb
<div id="chat1">
  <%= render :partial => "chats_list"%>
</div>
<div id="chat">
  <%= render :partial => "chats"%>
</div>

app/views/posts/chat_index.js.erb
$("#chat").html("<%= escape_javascript(render("chats")) %>");
$("#chat1").html("<%= escape_javascript(render("chats_list")) %>");

app/views/posts/chat_refresh.html.erb
<script type="text/javascript">
    <!--

        /*
         Auto Refresh Page with Time script
         By JavaScript Kit (javascriptkit.com)
         Over 200+ free scripts here!
         */

//enter refresh time in "minutes:seconds" Minutes should range from 0 to inifinity. Seconds should range from 0 to 59
    var limit="0:05"

    if (document.images){
        var parselimit=limit.split(":")
        parselimit=parselimit[0]*60+parselimit[1]*1
    }
    function beginrefresh(){
        if (!document.images)
            return
        if (parselimit==1)
            window.location.reload()
        else{
            parselimit-=1
            curmin=Math.floor(parselimit/60)
            cursec=parselimit%60
            if (curmin!=0)
                curtime=curmin+" minutes and "+cursec+" seconds left until page refresh!"
            else
                curtime=cursec+" seconds left until page refresh!"
            window.status=curtime
            setTimeout("beginrefresh()",1000)
        }
    }

    window.onload=beginrefresh
    //-->
</script>


hiiiiiiiiiiiii   <br/>
<% @chats.each do |chats| %>
    <%= chats.user_id %>
    <%= chats.body %>     <br/>
<% end %>

app/views/posts/edit.html.erb
<h2 align= "center">
  <%=form_for(@post) do |n|  %>
<%=n.label 'name'%>
<%= n.text_field 'name'%><br /><br />
<%=n.label 'title'%>
<%= n.text_field 'title'%><br /><br />
<%= n.label 'description'%>
<%= n.text_field 'description' %><br /><br />
<%= n.submit %>
<% end %>
<%= link_to 'show', @post %>
<%=link_to "Back" ,:controller=>'posts',:action=> 'new'%>
</h2>

app/views/posts/index.html.erb
<div style="width:471px;height:auto;margin: 0px auto;">
      <br/>
<%=form_for :post,:url=>{:action=>'create'} do |n|  %>
    <%= n.text_area :description ,:rows=>2,:cols=>64,:class=>'input_text_area'%>
    <%= n.hidden_field :user_id,:value=>session[:user_id] %> <br/> <br/>
    <%= n.submit "post",:class=>'button2' %>
<% end %>
</div>
<div id="chat">
  <%= render :partial => "chats"%>
</div>

app/views/posts/new.html.erb
<%=form_for(@post) do |n|  %>
<%=n.label 'name'%>
<%= n.text_field 'name'%><br /><br />
<%=n.label 'title'%>
<%= n.text_field 'title'%><br /><br />
<%= n.label 'description'%>
<%= n.text_field 'description' %>
    <%= n.hidden_field 'user_id',:value=>session[:user_id] %>
<%= n.submit %>
<% end %>
<%=link_to "Back" ,:controller=>'posts',:action=> 'index'%>

app/views/posts/show.html.erb
<div class="post_div" style="color:black;">

       <%@usr= Users.find(@post.user_id) %>
  <h4 class="poster"><%=@usr.username %></h4> </br>
  <h3 style="margin-left: 50px;"><%= @post.description %></h3>
    </div>

<div id="fetch"><%= render :partial => "comment"%></div>

<!--<h3>Add a comment:</h3>
<%#= form_tag(comment_post_path(@post),:method => 'post') do %>
:commenter
<%#= text_field_tag "comment[commenter]" %>
:message
<%#= text_area_tag "comment[message]" %>


<div id="comment"><%#= button_tag "comment", :id=>"comment_tag"%></div>
<%#end %>-->

<%#= link_to 'Edit', edit_post_path(@post) %> |
<%#= link_to 'Back' ,:controller => 'posts', :action=> 'index' %>

app/views/posts/show.js.erb
$("#fetch").html("<%= escape_javascript(render("comment")) %>");

app/views/settings/index.html.erb
<br/>     <br/><br/>
hii


<%=form_for :setting do |sett|%>
    <%=sett.hidden_field :user_id,:value=>'session[:user_id]'%>   <br/>

    level of security:<%=sett.select :security_level,["Post","Comments"]%>     <br/>


    <% @members.each do |member| %>
    <%=sett.check_box "username#{member.id}"%> <%= member.username %>     <br/>
        <% end %>
    <br/>
    <%=sett.submit "submit"%>
<%end%>

app/views/user/member_profile.html.erb
  <div class="member">
<div style="border:1px solid #BFEBFB;padding: 15px;margin: 1px;">
  <b>Username</b>&nbsp;:<span style="padding: 40px;"><%= @mem_profile.username %> </span>
</div>
<div style="border:1px solid #BFEBFB;padding: 15px;margin: 1px;">
  <b>E-mail&nbsp;&nbsp;&nbsp;</b>:<span style="padding: 40px;"><%= @mem_profile.email %> </span>
</div>
<div style="border:1px solid #BFEBFB;padding: 15px;margin: 1px;">
  <b>Date of birth&nbsp;</b>:<span style="padding: 40px;"><%= @mem_profile.date_of_birth %> </span>
</div>
</div>

app/views/user/photo.erb
<br/>
<br/>
<br/>
<%= form_for :album do |f| %>
    <h4>
      &nbsp;&nbsp;&nbsp;&nbsp; <label>My Avatar</label>
      <%#= f.file_field :image %>
      <%= f.file_field :avatar %>
      <%= f.hidden_field :avatar_cache %>
      <br/>
      <br/>
      &nbsp;&nbsp;&nbsp;&nbsp;Set As Profile Pic <%= f.radio_button :profile_picture, true  %> Yes
      <%= f.radio_button :profile_picture, false ,:checked=>true %> No
    </h4>
    <%=f.submit "Upload Photo"%>
<% end %>

app/views/user/profile.html.erb
  <div style="border:1px solid #BFEBFB;padding: 15px;margin: 1px;">
    <b>Username</b>&nbsp;:<span style="padding: 40px;"><%= @current_user_id.username %> </span>
  </div>
  <div style="border:1px solid #BFEBFB;padding: 15px;margin: 1px;">
    <b>E-mail&nbsp;&nbsp;&nbsp;</b>:<span style="padding: 40px;"><%= @current_user_id.email %> </span>
  </div>
  <div style="border:1px solid #BFEBFB;padding: 15px;margin: 1px;">
    <b>Date of birth&nbsp;</b>:<span style="padding: 40px;"><%= @current_user_id.date_of_birth %> </span>
  </div>
  <%@albums=Album.find_all_by_users_id_and_profile_picture(@current_user_id,false)%>
  <%unless @albums.nil?%>
  <%#if (@albums.avatar).blank? %>
       no image

      <%#else%>
      <%for album in @albums%>
      <%= image_tag album.avatar_url  %>
          <%end%>
  <%end%>
    <%#end%>
  <%=link_to "profile image",:controller=>"user", :action=>"photo"%>